/* tslint:disable */
/* eslint-disable */
/**
 * Jelly
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateToiletRatingDto,
    CreateToiletRatingDtoFromJSON,
    CreateToiletRatingDtoToJSON,
} from '../models/CreateToiletRatingDto';

export interface ToiletsControllerAddRatingRequest {
    id: number;
    createToiletRatingDto: CreateToiletRatingDto;
}

export interface ToiletsControllerCreateToiletRequest {
    createToiletRatingDto: CreateToiletRatingDto;
}

export interface ToiletsControllerGetRatingsByToiletRequest {
    id: number;
}

export interface ToiletsControllerGetToiletByIdRequest {
    id: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for toiletsControllerAddRating without sending the request
     */
    async toiletsControllerAddRatingRequestOpts(requestParameters: ToiletsControllerAddRatingRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toiletsControllerAddRating().'
            );
        }

        if (requestParameters['createToiletRatingDto'] == null) {
            throw new runtime.RequiredError(
                'createToiletRatingDto',
                'Required parameter "createToiletRatingDto" was null or undefined when calling toiletsControllerAddRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/toilets/{id}/ratings`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateToiletRatingDtoToJSON(requestParameters['createToiletRatingDto']),
        };
    }

    /**
     * Добавить отзыв к туалету
     */
    async toiletsControllerAddRatingRaw(requestParameters: ToiletsControllerAddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateToiletRatingDto>> {
        const requestOptions = await this.toiletsControllerAddRatingRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateToiletRatingDtoFromJSON(jsonValue));
    }

    /**
     * Добавить отзыв к туалету
     */
    async toiletsControllerAddRating(requestParameters: ToiletsControllerAddRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateToiletRatingDto> {
        const response = await this.toiletsControllerAddRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toiletsControllerCreateToilet without sending the request
     */
    async toiletsControllerCreateToiletRequestOpts(requestParameters: ToiletsControllerCreateToiletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createToiletRatingDto'] == null) {
            throw new runtime.RequiredError(
                'createToiletRatingDto',
                'Required parameter "createToiletRatingDto" was null or undefined when calling toiletsControllerCreateToilet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/toilets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateToiletRatingDtoToJSON(requestParameters['createToiletRatingDto']),
        };
    }

    /**
     * Создать новый туалет
     */
    async toiletsControllerCreateToiletRaw(requestParameters: ToiletsControllerCreateToiletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateToiletRatingDto>> {
        const requestOptions = await this.toiletsControllerCreateToiletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateToiletRatingDtoFromJSON(jsonValue));
    }

    /**
     * Создать новый туалет
     */
    async toiletsControllerCreateToilet(requestParameters: ToiletsControllerCreateToiletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateToiletRatingDto> {
        const response = await this.toiletsControllerCreateToiletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toiletsControllerGetAllRatings without sending the request
     */
    async toiletsControllerGetAllRatingsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/toilets/ratings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить все отзывы
     */
    async toiletsControllerGetAllRatingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreateToiletRatingDto>>> {
        const requestOptions = await this.toiletsControllerGetAllRatingsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreateToiletRatingDtoFromJSON));
    }

    /**
     * Получить все отзывы
     */
    async toiletsControllerGetAllRatings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreateToiletRatingDto>> {
        const response = await this.toiletsControllerGetAllRatingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toiletsControllerGetAllToilets without sending the request
     */
    async toiletsControllerGetAllToiletsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/toilets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить все туалеты с отзывами
     */
    async toiletsControllerGetAllToiletsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreateToiletRatingDto>>> {
        const requestOptions = await this.toiletsControllerGetAllToiletsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreateToiletRatingDtoFromJSON));
    }

    /**
     * Получить все туалеты с отзывами
     */
    async toiletsControllerGetAllToilets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreateToiletRatingDto>> {
        const response = await this.toiletsControllerGetAllToiletsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toiletsControllerGetRatingsByToilet without sending the request
     */
    async toiletsControllerGetRatingsByToiletRequestOpts(requestParameters: ToiletsControllerGetRatingsByToiletRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toiletsControllerGetRatingsByToilet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/toilets/{id}/ratings`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить все отзывы конкретного туалета
     */
    async toiletsControllerGetRatingsByToiletRaw(requestParameters: ToiletsControllerGetRatingsByToiletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreateToiletRatingDto>>> {
        const requestOptions = await this.toiletsControllerGetRatingsByToiletRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreateToiletRatingDtoFromJSON));
    }

    /**
     * Получить все отзывы конкретного туалета
     */
    async toiletsControllerGetRatingsByToilet(requestParameters: ToiletsControllerGetRatingsByToiletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreateToiletRatingDto>> {
        const response = await this.toiletsControllerGetRatingsByToiletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toiletsControllerGetToiletById without sending the request
     */
    async toiletsControllerGetToiletByIdRequestOpts(requestParameters: ToiletsControllerGetToiletByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toiletsControllerGetToiletById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/toilets/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить туалет по ID с его отзывами
     */
    async toiletsControllerGetToiletByIdRaw(requestParameters: ToiletsControllerGetToiletByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateToiletRatingDto>> {
        const requestOptions = await this.toiletsControllerGetToiletByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateToiletRatingDtoFromJSON(jsonValue));
    }

    /**
     * Получить туалет по ID с его отзывами
     */
    async toiletsControllerGetToiletById(requestParameters: ToiletsControllerGetToiletByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateToiletRatingDto> {
        const response = await this.toiletsControllerGetToiletByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
