/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AnalyticsCreate,
    AnalyticsCreateFromJSON,
    AnalyticsCreateToJSON,
} from '../models/AnalyticsCreate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateAnalyticsAnalyticsPostRequest {
    analyticsCreate: AnalyticsCreate;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAnalyticsAnalyticsPost without sending the request
     */
    async createAnalyticsAnalyticsPostRequestOpts(requestParameters: CreateAnalyticsAnalyticsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['analyticsCreate'] == null) {
            throw new runtime.RequiredError(
                'analyticsCreate',
                'Required parameter "analyticsCreate" was null or undefined when calling createAnalyticsAnalyticsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/analytics/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnalyticsCreateToJSON(requestParameters['analyticsCreate']),
        };
    }

    /**
     * Добаление отзыва
     * Create Analytics
     */
    async createAnalyticsAnalyticsPostRaw(requestParameters: CreateAnalyticsAnalyticsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createAnalyticsAnalyticsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Добаление отзыва
     * Create Analytics
     */
    async createAnalyticsAnalyticsPost(requestParameters: CreateAnalyticsAnalyticsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createAnalyticsAnalyticsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for fetchAllAnalyticsGet without sending the request
     */
    async fetchAllAnalyticsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/analytics/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получение аналитики
     * Fetch All
     */
    async fetchAllAnalyticsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.fetchAllAnalyticsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Получение аналитики
     * Fetch All
     */
    async fetchAllAnalyticsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.fetchAllAnalyticsGetRaw(initOverrides);
        return await response.value();
    }

}
