/* tslint:disable */
/* eslint-disable */
/**
 * QR Toilet API
 * API для оценки состояния туалетов по QR кодам
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ModelsToiletRating,
    ModelsToiletRatingFromJSON,
    ModelsToiletRatingToJSON,
} from '../models/ModelsToiletRating';

export interface ApiToiletsIdRatingsGetRequest {
    id: number;
}

export interface ApiToiletsIdRatingsPostRequest {
    id: number;
    rating: ModelsToiletRating;
}

/**
 * 
 */
export class RatingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiToiletsIdRatingsGet without sending the request
     */
    async apiToiletsIdRatingsGetRequestOpts(requestParameters: ApiToiletsIdRatingsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiToiletsIdRatingsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/toilets/{id}/ratings`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить оценки туалета
     */
    async apiToiletsIdRatingsGetRaw(requestParameters: ApiToiletsIdRatingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsToiletRating>>> {
        const requestOptions = await this.apiToiletsIdRatingsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsToiletRatingFromJSON));
    }

    /**
     * Получить оценки туалета
     */
    async apiToiletsIdRatingsGet(requestParameters: ApiToiletsIdRatingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsToiletRating>> {
        const response = await this.apiToiletsIdRatingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiToiletsIdRatingsPost without sending the request
     */
    async apiToiletsIdRatingsPostRequestOpts(requestParameters: ApiToiletsIdRatingsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiToiletsIdRatingsPost().'
            );
        }

        if (requestParameters['rating'] == null) {
            throw new runtime.RequiredError(
                'rating',
                'Required parameter "rating" was null or undefined when calling apiToiletsIdRatingsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/toilets/{id}/ratings`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsToiletRatingToJSON(requestParameters['rating']),
        };
    }

    /**
     * Добавить оценку туалету
     */
    async apiToiletsIdRatingsPostRaw(requestParameters: ApiToiletsIdRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsToiletRating>> {
        const requestOptions = await this.apiToiletsIdRatingsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsToiletRatingFromJSON(jsonValue));
    }

    /**
     * Добавить оценку туалету
     */
    async apiToiletsIdRatingsPost(requestParameters: ApiToiletsIdRatingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsToiletRating> {
        const response = await this.apiToiletsIdRatingsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
