/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type TestCreate,
    TestCreateFromJSON,
    TestCreateToJSON,
} from '../models/TestCreate';

export interface CreateRecordTestPostRequest {
    testCreate: TestCreate;
}

/**
 * 
 */
export class TestApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRecordTestPost without sending the request
     */
    async createRecordTestPostRequestOpts(requestParameters: CreateRecordTestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['testCreate'] == null) {
            throw new runtime.RequiredError(
                'testCreate',
                'Required parameter "testCreate" was null or undefined when calling createRecordTestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/test/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TestCreateToJSON(requestParameters['testCreate']),
        };
    }

    /**
     * Добавление записи
     * Create Record
     */
    async createRecordTestPostRaw(requestParameters: CreateRecordTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createRecordTestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Добавление записи
     * Create Record
     */
    async createRecordTestPost(requestParameters: CreateRecordTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createRecordTestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for fetchTestGet without sending the request
     */
    async fetchTestGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/test/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Тестовый эндпоинт
     * Fetch
     */
    async fetchTestGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.fetchTestGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Тестовый эндпоинт
     * Fetch
     */
    async fetchTestGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.fetchTestGetRaw(initOverrides);
        return await response.value();
    }

}
