/* tslint:disable */
/* eslint-disable */
/**
 * QR Toilet API
 * API для оценки состояния туалетов по QR кодам
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ModelsToilet,
    ModelsToiletFromJSON,
    ModelsToiletToJSON,
} from '../models/ModelsToilet';

/**
 * 
 */
export class ToiletsApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiToiletsGet without sending the request
     */
    async apiToiletsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/toilets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Получить список туалетов
     */
    async apiToiletsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsToilet>>> {
        const requestOptions = await this.apiToiletsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsToiletFromJSON));
    }

    /**
     * Получить список туалетов
     */
    async apiToiletsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsToilet>> {
        const response = await this.apiToiletsGetRaw(initOverrides);
        return await response.value();
    }

}
