services:
  # init:
  #   container_name: "init"
  #   build:
  #     context: ./init
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"

  init:
    container_name: "init"
    build:
      context: ./init
      dockerfile: Dockerfile
    networks:
      - traefik-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.init-web.rule=Host(`fesmu.promotion-pal.ru`)"
      - "traefik.http.routers.init-web.entrypoints=web"
      - "traefik.http.routers.init-web.middlewares=redirect-to-https"
      - "traefik.http.routers.init-web-secure.rule=Host(`fesmu.promotion-pal.ru`)"
      - "traefik.http.routers.init-web-secure.entrypoints=websecure"
      - "traefik.http.routers.init-web-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.init-web.loadbalancer.server.port=8040"

networks:
  traefik-network:
    external: true
