services:
  postgres:
    container_name: "fesmu"
    image: postgres:17
    env_file:
      - .env
    ports:
      - "${SERVER_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
