/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ModelsUser,
    ModelsUserFromJSON,
    ModelsUserToJSON,
} from '../models/ModelsUser';

export interface UsersEmailEmailGetRequest {
    email: string;
}

export interface UsersIdDeleteRequest {
    id: number;
}

export interface UsersIdGetRequest {
    id: number;
}

export interface UsersIdPutRequest {
    id: number;
    user: ModelsUser;
}

export interface UsersIdRolePatchRequest {
    id: number;
    role: string;
}

export interface UsersPostRequest {
    user: ModelsUser;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersEmailEmailGet without sending the request
     */
    async usersEmailEmailGetRequestOpts(requestParameters: UsersEmailEmailGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling usersEmailEmailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/email/{email}`;
        urlPath = urlPath.replace('{email}', encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ищет и возвращает профиль пользователя по его электронной почте
     * Найти пользователя по Email
     */
    async usersEmailEmailGetRaw(requestParameters: UsersEmailEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsUser>> {
        const requestOptions = await this.usersEmailEmailGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUserFromJSON(jsonValue));
    }

    /**
     * Ищет и возвращает профиль пользователя по его электронной почте
     * Найти пользователя по Email
     */
    async usersEmailEmailGet(requestParameters: UsersEmailEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsUser> {
        const response = await this.usersEmailEmailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersGet without sending the request
     */
    async usersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает массив всех зарегистрированных пользователей
     * Получить список пользователей
     */
    async usersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsUser>>> {
        const requestOptions = await this.usersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsUserFromJSON));
    }

    /**
     * Возвращает массив всех зарегистрированных пользователей
     * Получить список пользователей
     */
    async usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsUser>> {
        const response = await this.usersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdDelete without sending the request
     */
    async usersIdDeleteRequestOpts(requestParameters: UsersIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Удаляет запись о пользователе из базы данных по его ID
     * Удалить пользователя
     */
    async usersIdDeleteRaw(requestParameters: UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.usersIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Удаляет запись о пользователе из базы данных по его ID
     * Удалить пользователя
     */
    async usersIdDelete(requestParameters: UsersIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.usersIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdGet without sending the request
     */
    async usersIdGetRequestOpts(requestParameters: UsersIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает профиль пользователя по его числовому идентификатору
     * Получить пользователя по ID
     */
    async usersIdGetRaw(requestParameters: UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsUser>> {
        const requestOptions = await this.usersIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUserFromJSON(jsonValue));
    }

    /**
     * Возвращает профиль пользователя по его числовому идентификатору
     * Получить пользователя по ID
     */
    async usersIdGet(requestParameters: UsersIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsUser> {
        const response = await this.usersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdPut without sending the request
     */
    async usersIdPutRequestOpts(requestParameters: UsersIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdPut().'
            );
        }

        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsUserToJSON(requestParameters['user']),
        };
    }

    /**
     * Полностью обновляет информацию о пользователе по его ID
     * Обновить профиль пользователя
     */
    async usersIdPutRaw(requestParameters: UsersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.usersIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Полностью обновляет информацию о пользователе по его ID
     * Обновить профиль пользователя
     */
    async usersIdPut(requestParameters: UsersIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.usersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersIdRolePatch without sending the request
     */
    async usersIdRolePatchRequestOpts(requestParameters: UsersIdRolePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling usersIdRolePatch().'
            );
        }

        if (requestParameters['role'] == null) {
            throw new runtime.RequiredError(
                'role',
                'Required parameter "role" was null or undefined when calling usersIdRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{id}/role`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['role'] as any,
        };
    }

    /**
     * Частичное обновление: изменяет только роль пользователя (например, admin, user)
     * Обновить роль пользователя
     */
    async usersIdRolePatchRaw(requestParameters: UsersIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.usersIdRolePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Частичное обновление: изменяет только роль пользователя (например, admin, user)
     * Обновить роль пользователя
     */
    async usersIdRolePatch(requestParameters: UsersIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.usersIdRolePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersPost without sending the request
     */
    async usersPostRequestOpts(requestParameters: UsersPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling usersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsUserToJSON(requestParameters['user']),
        };
    }

    /**
     * Регистрирует нового пользователя. Поля name, email и password обязательны.
     * Создать пользователя
     */
    async usersPostRaw(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsUser>> {
        const requestOptions = await this.usersPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUserFromJSON(jsonValue));
    }

    /**
     * Регистрирует нового пользователя. Поля name, email и password обязательны.
     * Создать пользователя
     */
    async usersPost(requestParameters: UsersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsUser> {
        const response = await this.usersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
