// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/toilets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "toilets"
                ],
                "summary": "Получить список туалетов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Toilet"
                            }
                        }
                    }
                }
            }
        },
        "/api/toilets/{id}/ratings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ratings"
                ],
                "summary": "Получить оценки туалета",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID туалета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ToiletRating"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ratings"
                ],
                "summary": "Добавить оценку туалету",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID туалета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные оценки",
                        "name": "rating",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ToiletRating"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ToiletRating"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Toilet": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Центральный туалет"
                },
                "rating": {
                    "type": "number",
                    "example": 4.5
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                }
            }
        },
        "models.ToiletRating": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "Чисто, есть мыло"
                },
                "condition_room": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 8
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-11T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "soap_available": {
                    "type": "boolean",
                    "example": true
                },
                "toilet_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "QR Toilet API",
	Description:      "API для оценки состояния туалетов по QR кодам",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
