/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ModelsApplicationEntity,
    ModelsApplicationEntityFromJSON,
    ModelsApplicationEntityToJSON,
} from '../models/ModelsApplicationEntity';
import {
    type ServiceApplicationCreateDto,
    ServiceApplicationCreateDtoFromJSON,
    ServiceApplicationCreateDtoToJSON,
} from '../models/ServiceApplicationCreateDto';

export interface ApplicationsIdDeleteRequest {
    id: number;
}

export interface ApplicationsIdGetRequest {
    id: number;
}

export interface ApplicationsIdPutRequest {
    id: number;
    application: ServiceApplicationCreateDto;
}

export interface ApplicationsPostRequest {
    application: ServiceApplicationCreateDto;
}

/**
 * 
 */
export class ApplicationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for applicationsGet without sending the request
     */
    async applicationsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/applications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает массив всех поданных заявок в системе
     * Получить список всех заявок
     */
    async applicationsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsApplicationEntity>>> {
        const requestOptions = await this.applicationsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsApplicationEntityFromJSON));
    }

    /**
     * Возвращает массив всех поданных заявок в системе
     * Получить список всех заявок
     */
    async applicationsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsApplicationEntity>> {
        const response = await this.applicationsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for applicationsIdDelete without sending the request
     */
    async applicationsIdDeleteRequestOpts(requestParameters: ApplicationsIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/applications/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Удаляет запись о заявке из базы данных по её уникальному ID
     * Удалить заявку
     */
    async applicationsIdDeleteRaw(requestParameters: ApplicationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.applicationsIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Удаляет запись о заявке из базы данных по её уникальному ID
     * Удалить заявку
     */
    async applicationsIdDelete(requestParameters: ApplicationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.applicationsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for applicationsIdGet without sending the request
     */
    async applicationsIdGetRequestOpts(requestParameters: ApplicationsIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/applications/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает полную информацию о конкретной заявке по её идентификатору
     * Получить заявку по ID
     */
    async applicationsIdGetRaw(requestParameters: ApplicationsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsApplicationEntity>> {
        const requestOptions = await this.applicationsIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsApplicationEntityFromJSON(jsonValue));
    }

    /**
     * Возвращает полную информацию о конкретной заявке по её идентификатору
     * Получить заявку по ID
     */
    async applicationsIdGet(requestParameters: ApplicationsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsApplicationEntity> {
        const response = await this.applicationsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for applicationsIdPut without sending the request
     */
    async applicationsIdPutRequestOpts(requestParameters: ApplicationsIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsIdPut().'
            );
        }

        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling applicationsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/applications/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceApplicationCreateDtoToJSON(requestParameters['application']),
        };
    }

    /**
     * Полностью перезаписывает информацию в существующей заявке по её ID
     * Обновить данные заявки
     */
    async applicationsIdPutRaw(requestParameters: ApplicationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.applicationsIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Полностью перезаписывает информацию в существующей заявке по её ID
     * Обновить данные заявки
     */
    async applicationsIdPut(requestParameters: ApplicationsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.applicationsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for applicationsPost without sending the request
     */
    async applicationsPostRequestOpts(requestParameters: ApplicationsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling applicationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/applications`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceApplicationCreateDtoToJSON(requestParameters['application']),
        };
    }

    /**
     * Принимает данные заявки и привязывает её к текущему авторизованному пользователю
     * Создать новую заявку
     */
    async applicationsPostRaw(requestParameters: ApplicationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceApplicationCreateDto>> {
        const requestOptions = await this.applicationsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceApplicationCreateDtoFromJSON(jsonValue));
    }

    /**
     * Принимает данные заявки и привязывает её к текущему авторизованному пользователю
     * Создать новую заявку
     */
    async applicationsPost(requestParameters: ApplicationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceApplicationCreateDto> {
        const response = await this.applicationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
