/* tslint:disable */
/* eslint-disable */
/**
 * Jelly
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateToiletRatingDto
 */
export interface CreateToiletRatingDto {
    /**
     * Оценка запаха от 1 до 5
     * @type {number}
     * @memberof CreateToiletRatingDto
     */
    smellRating: number;
    /**
     * Оценка чистоты от 1 до 5
     * @type {number}
     * @memberof CreateToiletRatingDto
     */
    purityRating: number;
    /**
     * Наличие туалетной бумаги
     * @type {boolean}
     * @memberof CreateToiletRatingDto
     */
    hasToiletPaper: boolean;
    /**
     * Наличие мыла
     * @type {boolean}
     * @memberof CreateToiletRatingDto
     */
    hasSoap: boolean;
    /**
     * Комментарий пользователя
     * @type {string}
     * @memberof CreateToiletRatingDto
     */
    comment: string;
}

/**
 * Check if a given object implements the CreateToiletRatingDto interface.
 */
export function instanceOfCreateToiletRatingDto(value: object): value is CreateToiletRatingDto {
    if (!('smellRating' in value) || value['smellRating'] === undefined) return false;
    if (!('purityRating' in value) || value['purityRating'] === undefined) return false;
    if (!('hasToiletPaper' in value) || value['hasToiletPaper'] === undefined) return false;
    if (!('hasSoap' in value) || value['hasSoap'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function CreateToiletRatingDtoFromJSON(json: any): CreateToiletRatingDto {
    return CreateToiletRatingDtoFromJSONTyped(json, false);
}

export function CreateToiletRatingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToiletRatingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'smellRating': json['smellRating'],
        'purityRating': json['purityRating'],
        'hasToiletPaper': json['hasToiletPaper'],
        'hasSoap': json['hasSoap'],
        'comment': json['comment'],
    };
}

export function CreateToiletRatingDtoToJSON(json: any): CreateToiletRatingDto {
    return CreateToiletRatingDtoToJSONTyped(json, false);
}

export function CreateToiletRatingDtoToJSONTyped(value?: CreateToiletRatingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'smellRating': value['smellRating'],
        'purityRating': value['purityRating'],
        'hasToiletPaper': value['hasToiletPaper'],
        'hasSoap': value['hasSoap'],
        'comment': value['comment'],
    };
}

