/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LectureHallCreateDto
 */
export interface LectureHallCreateDto {
    /**
     * Название или местоположение
     * @type {string}
     * @memberof LectureHallCreateDto
     */
    name?: string;
    /**
     * Местоположение
     * @type {LectureHallCreateDtoLocationEnum}
     * @memberof LectureHallCreateDto
     */
    location: LectureHallCreateDtoLocationEnum;
}


/**
 * @export
 */
export const LectureHallCreateDtoLocationEnum = {
    FirstBuilding: 'first_building',
    ThirdBuilding: 'third_building',
    SecondBuilding: 'second_building'
} as const;
export type LectureHallCreateDtoLocationEnum = typeof LectureHallCreateDtoLocationEnum[keyof typeof LectureHallCreateDtoLocationEnum];


/**
 * Check if a given object implements the LectureHallCreateDto interface.
 */
export function instanceOfLectureHallCreateDto(value: object): value is LectureHallCreateDto {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function LectureHallCreateDtoFromJSON(json: any): LectureHallCreateDto {
    return LectureHallCreateDtoFromJSONTyped(json, false);
}

export function LectureHallCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureHallCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'],
    };
}

export function LectureHallCreateDtoToJSON(json: any): LectureHallCreateDto {
    return LectureHallCreateDtoToJSONTyped(json, false);
}

export function LectureHallCreateDtoToJSONTyped(value?: LectureHallCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
    };
}

