/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LectureHallRatingCreateDto
 */
export interface LectureHallRatingCreateDto {
    /**
     * Комментарий пользователя
     * @type {string}
     * @memberof LectureHallRatingCreateDto
     */
    comment: string;
    /**
     * Чистота в зале
     * @type {number}
     * @memberof LectureHallRatingCreateDto
     */
    cleanliness: number;
    /**
     * Комфортность
     * @type {number}
     * @memberof LectureHallRatingCreateDto
     */
    comfort: number;
    /**
     * Оснащённость орг. техникой
     * @type {number}
     * @memberof LectureHallRatingCreateDto
     */
    equipment: number;
}

/**
 * Check if a given object implements the LectureHallRatingCreateDto interface.
 */
export function instanceOfLectureHallRatingCreateDto(value: object): value is LectureHallRatingCreateDto {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('cleanliness' in value) || value['cleanliness'] === undefined) return false;
    if (!('comfort' in value) || value['comfort'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    return true;
}

export function LectureHallRatingCreateDtoFromJSON(json: any): LectureHallRatingCreateDto {
    return LectureHallRatingCreateDtoFromJSONTyped(json, false);
}

export function LectureHallRatingCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureHallRatingCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'cleanliness': json['cleanliness'],
        'comfort': json['comfort'],
        'equipment': json['equipment'],
    };
}

export function LectureHallRatingCreateDtoToJSON(json: any): LectureHallRatingCreateDto {
    return LectureHallRatingCreateDtoToJSONTyped(json, false);
}

export function LectureHallRatingCreateDtoToJSONTyped(value?: LectureHallRatingCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'cleanliness': value['cleanliness'],
        'comfort': value['comfort'],
        'equipment': value['equipment'],
    };
}

