/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LectureHallRatingEntity
 */
export interface LectureHallRatingEntity {
    /**
     * Уникальный идентификатор оценки
     * @type {number}
     * @memberof LectureHallRatingEntity
     */
    id: number;
    /**
     * Комментарий пользователя
     * @type {string}
     * @memberof LectureHallRatingEntity
     */
    comment: string | null;
    /**
     * Дата создания записи
     * @type {Date}
     * @memberof LectureHallRatingEntity
     */
    createdAt: Date;
    /**
     * Дата последнего обновления
     * @type {Date}
     * @memberof LectureHallRatingEntity
     */
    updatedAt: Date;
    /**
     * Чистота в зале
     * @type {number}
     * @memberof LectureHallRatingEntity
     */
    cleanliness: number;
    /**
     * Комфортность
     * @type {number}
     * @memberof LectureHallRatingEntity
     */
    comfort: number;
    /**
     * Оснащённость орг. техникой
     * @type {number}
     * @memberof LectureHallRatingEntity
     */
    equipment: number;
}

/**
 * Check if a given object implements the LectureHallRatingEntity interface.
 */
export function instanceOfLectureHallRatingEntity(value: object): value is LectureHallRatingEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('cleanliness' in value) || value['cleanliness'] === undefined) return false;
    if (!('comfort' in value) || value['comfort'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    return true;
}

export function LectureHallRatingEntityFromJSON(json: any): LectureHallRatingEntity {
    return LectureHallRatingEntityFromJSONTyped(json, false);
}

export function LectureHallRatingEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureHallRatingEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'comment': json['comment'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'cleanliness': json['cleanliness'],
        'comfort': json['comfort'],
        'equipment': json['equipment'],
    };
}

export function LectureHallRatingEntityToJSON(json: any): LectureHallRatingEntity {
    return LectureHallRatingEntityToJSONTyped(json, false);
}

export function LectureHallRatingEntityToJSONTyped(value?: LectureHallRatingEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'comment': value['comment'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'cleanliness': value['cleanliness'],
        'comfort': value['comfort'],
        'equipment': value['equipment'],
    };
}

