/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LectureHallRatingResDto
 */
export interface LectureHallRatingResDto {
    /**
     * Чистота в зале
     * @type {number}
     * @memberof LectureHallRatingResDto
     */
    cleanliness: number;
    /**
     * Комфортность
     * @type {number}
     * @memberof LectureHallRatingResDto
     */
    comfort: number;
    /**
     * Оснащённость орг. техникой
     * @type {number}
     * @memberof LectureHallRatingResDto
     */
    equipment: number;
    /**
     * Уникальный идентификатор
     * @type {number}
     * @memberof LectureHallRatingResDto
     */
    id: number;
    /**
     * Дата создания записи
     * @type {Date}
     * @memberof LectureHallRatingResDto
     */
    createdAt: Date;
    /**
     * Дата последнего обновления
     * @type {Date}
     * @memberof LectureHallRatingResDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the LectureHallRatingResDto interface.
 */
export function instanceOfLectureHallRatingResDto(value: object): value is LectureHallRatingResDto {
    if (!('cleanliness' in value) || value['cleanliness'] === undefined) return false;
    if (!('comfort' in value) || value['comfort'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function LectureHallRatingResDtoFromJSON(json: any): LectureHallRatingResDto {
    return LectureHallRatingResDtoFromJSONTyped(json, false);
}

export function LectureHallRatingResDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureHallRatingResDto {
    if (json == null) {
        return json;
    }
    return {
        
        'cleanliness': json['cleanliness'],
        'comfort': json['comfort'],
        'equipment': json['equipment'],
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function LectureHallRatingResDtoToJSON(json: any): LectureHallRatingResDto {
    return LectureHallRatingResDtoToJSONTyped(json, false);
}

export function LectureHallRatingResDtoToJSONTyped(value?: LectureHallRatingResDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cleanliness': value['cleanliness'],
        'comfort': value['comfort'],
        'equipment': value['equipment'],
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

