/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LectureHallRatingEntity } from './LectureHallRatingEntity';
import {
    LectureHallRatingEntityFromJSON,
    LectureHallRatingEntityFromJSONTyped,
    LectureHallRatingEntityToJSON,
    LectureHallRatingEntityToJSONTyped,
} from './LectureHallRatingEntity';

/**
 * 
 * @export
 * @interface LectureHallResDto
 */
export interface LectureHallResDto {
    /**
     * Название или местоположение
     * @type {string}
     * @memberof LectureHallResDto
     */
    name?: string;
    /**
     * Местоположение
     * @type {LectureHallResDtoLocationEnum}
     * @memberof LectureHallResDto
     */
    location: LectureHallResDtoLocationEnum;
    /**
     * Уникальный идентификатор
     * @type {number}
     * @memberof LectureHallResDto
     */
    id: number;
    /**
     * Дата создания записи
     * @type {Date}
     * @memberof LectureHallResDto
     */
    createdAt: Date;
    /**
     * Дата последнего обновления
     * @type {Date}
     * @memberof LectureHallResDto
     */
    updatedAt: Date;
    /**
     * Список оценок
     * @type {Array<LectureHallRatingEntity>}
     * @memberof LectureHallResDto
     */
    ratings: Array<LectureHallRatingEntity>;
}


/**
 * @export
 */
export const LectureHallResDtoLocationEnum = {
    FirstBuilding: 'first_building',
    ThirdBuilding: 'third_building',
    SecondBuilding: 'second_building'
} as const;
export type LectureHallResDtoLocationEnum = typeof LectureHallResDtoLocationEnum[keyof typeof LectureHallResDtoLocationEnum];


/**
 * Check if a given object implements the LectureHallResDto interface.
 */
export function instanceOfLectureHallResDto(value: object): value is LectureHallResDto {
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('ratings' in value) || value['ratings'] === undefined) return false;
    return true;
}

export function LectureHallResDtoFromJSON(json: any): LectureHallResDto {
    return LectureHallResDtoFromJSONTyped(json, false);
}

export function LectureHallResDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureHallResDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'],
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'ratings': ((json['ratings'] as Array<any>).map(LectureHallRatingEntityFromJSON)),
    };
}

export function LectureHallResDtoToJSON(json: any): LectureHallResDto {
    return LectureHallResDtoToJSONTyped(json, false);
}

export function LectureHallResDtoToJSONTyped(value?: LectureHallResDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'ratings': ((value['ratings'] as Array<any>).map(LectureHallRatingEntityToJSON)),
    };
}

