/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToiletCreateRatingDto } from './ToiletCreateRatingDto';
import {
    ToiletCreateRatingDtoFromJSON,
    ToiletCreateRatingDtoFromJSONTyped,
    ToiletCreateRatingDtoToJSON,
    ToiletCreateRatingDtoToJSONTyped,
} from './ToiletCreateRatingDto';

/**
 * 
 * @export
 * @interface ToiletCreateDto
 */
export interface ToiletCreateDto {
    /**
     * Название или местоположение туалета
     * @type {string}
     * @memberof ToiletCreateDto
     */
    name: string;
    /**
     * Список оценок туалета
     * @type {Array<ToiletCreateRatingDto>}
     * @memberof ToiletCreateDto
     */
    ratings: Array<ToiletCreateRatingDto>;
}

/**
 * Check if a given object implements the ToiletCreateDto interface.
 */
export function instanceOfToiletCreateDto(value: object): value is ToiletCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ratings' in value) || value['ratings'] === undefined) return false;
    return true;
}

export function ToiletCreateDtoFromJSON(json: any): ToiletCreateDto {
    return ToiletCreateDtoFromJSONTyped(json, false);
}

export function ToiletCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToiletCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ratings': ((json['ratings'] as Array<any>).map(ToiletCreateRatingDtoFromJSON)),
    };
}

export function ToiletCreateDtoToJSON(json: any): ToiletCreateDto {
    return ToiletCreateDtoToJSONTyped(json, false);
}

export function ToiletCreateDtoToJSONTyped(value?: ToiletCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ratings': ((value['ratings'] as Array<any>).map(ToiletCreateRatingDtoToJSON)),
    };
}

