/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToiletCreateRatingDto
 */
export interface ToiletCreateRatingDto {
    /**
     * Оценка запаха от 1 до 5
     * @type {number}
     * @memberof ToiletCreateRatingDto
     */
    smellRating: number;
    /**
     * Оценка чистоты от 1 до 5
     * @type {number}
     * @memberof ToiletCreateRatingDto
     */
    purityRating: number;
    /**
     * Наличие туалетной бумаги
     * @type {boolean}
     * @memberof ToiletCreateRatingDto
     */
    hasToiletPaper: boolean;
    /**
     * Наличие мыла
     * @type {boolean}
     * @memberof ToiletCreateRatingDto
     */
    hasSoap: boolean;
    /**
     * Комментарий пользователя
     * @type {string}
     * @memberof ToiletCreateRatingDto
     */
    comment: string;
}

/**
 * Check if a given object implements the ToiletCreateRatingDto interface.
 */
export function instanceOfToiletCreateRatingDto(value: object): value is ToiletCreateRatingDto {
    if (!('smellRating' in value) || value['smellRating'] === undefined) return false;
    if (!('purityRating' in value) || value['purityRating'] === undefined) return false;
    if (!('hasToiletPaper' in value) || value['hasToiletPaper'] === undefined) return false;
    if (!('hasSoap' in value) || value['hasSoap'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function ToiletCreateRatingDtoFromJSON(json: any): ToiletCreateRatingDto {
    return ToiletCreateRatingDtoFromJSONTyped(json, false);
}

export function ToiletCreateRatingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToiletCreateRatingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'smellRating': json['smellRating'],
        'purityRating': json['purityRating'],
        'hasToiletPaper': json['hasToiletPaper'],
        'hasSoap': json['hasSoap'],
        'comment': json['comment'],
    };
}

export function ToiletCreateRatingDtoToJSON(json: any): ToiletCreateRatingDto {
    return ToiletCreateRatingDtoToJSONTyped(json, false);
}

export function ToiletCreateRatingDtoToJSONTyped(value?: ToiletCreateRatingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'smellRating': value['smellRating'],
        'purityRating': value['purityRating'],
        'hasToiletPaper': value['hasToiletPaper'],
        'hasSoap': value['hasSoap'],
        'comment': value['comment'],
    };
}

