/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToiletCreateRatingDto } from './ToiletCreateRatingDto';
import {
    ToiletCreateRatingDtoFromJSON,
    ToiletCreateRatingDtoFromJSONTyped,
    ToiletCreateRatingDtoToJSON,
    ToiletCreateRatingDtoToJSONTyped,
} from './ToiletCreateRatingDto';

/**
 * 
 * @export
 * @interface ToiletResDto
 */
export interface ToiletResDto {
    /**
     * Название или местоположение туалета
     * @type {string}
     * @memberof ToiletResDto
     */
    name: string;
    /**
     * Список оценок туалета
     * @type {Array<ToiletCreateRatingDto>}
     * @memberof ToiletResDto
     */
    ratings: Array<ToiletCreateRatingDto>;
    /**
     * Уникальный идентификатор туалета
     * @type {number}
     * @memberof ToiletResDto
     */
    id: number;
    /**
     * Дата создания записи
     * @type {Date}
     * @memberof ToiletResDto
     */
    createdAt: Date;
    /**
     * Дата последнего обновления
     * @type {Date}
     * @memberof ToiletResDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ToiletResDto interface.
 */
export function instanceOfToiletResDto(value: object): value is ToiletResDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ratings' in value) || value['ratings'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ToiletResDtoFromJSON(json: any): ToiletResDto {
    return ToiletResDtoFromJSONTyped(json, false);
}

export function ToiletResDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToiletResDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ratings': ((json['ratings'] as Array<any>).map(ToiletCreateRatingDtoFromJSON)),
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ToiletResDtoToJSON(json: any): ToiletResDto {
    return ToiletResDtoToJSONTyped(json, false);
}

export function ToiletResDtoToJSONTyped(value?: ToiletResDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ratings': ((value['ratings'] as Array<any>).map(ToiletCreateRatingDtoToJSON)),
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

