/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToiletRatingResDto
 */
export interface ToiletRatingResDto {
    /**
     * Оценка запаха от 1 до 5
     * @type {number}
     * @memberof ToiletRatingResDto
     */
    smellRating: number;
    /**
     * Оценка чистоты от 1 до 5
     * @type {number}
     * @memberof ToiletRatingResDto
     */
    purityRating: number;
    /**
     * Наличие туалетной бумаги
     * @type {boolean}
     * @memberof ToiletRatingResDto
     */
    hasToiletPaper: boolean;
    /**
     * Наличие мыла
     * @type {boolean}
     * @memberof ToiletRatingResDto
     */
    hasSoap: boolean;
    /**
     * Комментарий пользователя
     * @type {string}
     * @memberof ToiletRatingResDto
     */
    comment: string;
    /**
     * Уникальный идентификатор оценки
     * @type {number}
     * @memberof ToiletRatingResDto
     */
    id: number;
    /**
     * Дата создания записи
     * @type {Date}
     * @memberof ToiletRatingResDto
     */
    createdAt: Date;
    /**
     * Дата последнего обновления
     * @type {Date}
     * @memberof ToiletRatingResDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ToiletRatingResDto interface.
 */
export function instanceOfToiletRatingResDto(value: object): value is ToiletRatingResDto {
    if (!('smellRating' in value) || value['smellRating'] === undefined) return false;
    if (!('purityRating' in value) || value['purityRating'] === undefined) return false;
    if (!('hasToiletPaper' in value) || value['hasToiletPaper'] === undefined) return false;
    if (!('hasSoap' in value) || value['hasSoap'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ToiletRatingResDtoFromJSON(json: any): ToiletRatingResDto {
    return ToiletRatingResDtoFromJSONTyped(json, false);
}

export function ToiletRatingResDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToiletRatingResDto {
    if (json == null) {
        return json;
    }
    return {
        
        'smellRating': json['smellRating'],
        'purityRating': json['purityRating'],
        'hasToiletPaper': json['hasToiletPaper'],
        'hasSoap': json['hasSoap'],
        'comment': json['comment'],
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ToiletRatingResDtoToJSON(json: any): ToiletRatingResDto {
    return ToiletRatingResDtoToJSONTyped(json, false);
}

export function ToiletRatingResDtoToJSONTyped(value?: ToiletRatingResDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'smellRating': value['smellRating'],
        'purityRating': value['purityRating'],
        'hasToiletPaper': value['hasToiletPaper'],
        'hasSoap': value['hasSoap'],
        'comment': value['comment'],
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

