/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToiletCreateDto
 */
export interface ToiletCreateDto {
    /**
     * Название или местоположение туалета
     * @type {string}
     * @memberof ToiletCreateDto
     */
    name?: string;
    /**
     * Местоположение туалета
     * @type {ToiletCreateDtoLocationEnum}
     * @memberof ToiletCreateDto
     */
    location: ToiletCreateDtoLocationEnum;
    /**
     * Гендер
     * @type {ToiletCreateDtoPersonEnum}
     * @memberof ToiletCreateDto
     */
    person: ToiletCreateDtoPersonEnum;
    /**
     * 
     * @type {number}
     * @memberof ToiletCreateDto
     */
    floor: number;
}


/**
 * @export
 */
export const ToiletCreateDtoLocationEnum = {
    FirstBuilding: 'first_building',
    ThirdBuilding: 'third_building',
    SecondBuilding: 'second_building'
} as const;
export type ToiletCreateDtoLocationEnum = typeof ToiletCreateDtoLocationEnum[keyof typeof ToiletCreateDtoLocationEnum];

/**
 * @export
 */
export const ToiletCreateDtoPersonEnum = {
    Man: 'man',
    Woman: 'woman',
    Universal: 'universal'
} as const;
export type ToiletCreateDtoPersonEnum = typeof ToiletCreateDtoPersonEnum[keyof typeof ToiletCreateDtoPersonEnum];


/**
 * Check if a given object implements the ToiletCreateDto interface.
 */
export function instanceOfToiletCreateDto(value: object): value is ToiletCreateDto {
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('person' in value) || value['person'] === undefined) return false;
    if (!('floor' in value) || value['floor'] === undefined) return false;
    return true;
}

export function ToiletCreateDtoFromJSON(json: any): ToiletCreateDto {
    return ToiletCreateDtoFromJSONTyped(json, false);
}

export function ToiletCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToiletCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'location': json['location'],
        'person': json['person'],
        'floor': json['floor'],
    };
}

export function ToiletCreateDtoToJSON(json: any): ToiletCreateDto {
    return ToiletCreateDtoToJSONTyped(json, false);
}

export function ToiletCreateDtoToJSONTyped(value?: ToiletCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'location': value['location'],
        'person': value['person'],
        'floor': value['floor'],
    };
}

