/* tslint:disable */
/* eslint-disable */
/**
 * ДВГМУ Аналитика
 * API документация
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ToiletCreateRatingDto } from "./ToiletCreateRatingDto";
import {
  ToiletCreateRatingDtoFromJSON,
  ToiletCreateRatingDtoFromJSONTyped,
  ToiletCreateRatingDtoToJSON,
  ToiletCreateRatingDtoToJSONTyped,
} from "./ToiletCreateRatingDto";
import {
  ToiletRatingResDto,
  ToiletRatingResDtoFromJSON,
} from "./ToiletRatingResDto";

/**
 *
 * @export
 * @interface ToiletResDto
 */
export interface ToiletResDto {
  /**
   * Название или местоположение туалета
   * @type {string}
   * @memberof ToiletResDto
   */
  name?: string;
  /**
   * Местоположение туалета
   * @type {ToiletResDtoLocationEnum}
   * @memberof ToiletResDto
   */
  location: ToiletResDtoLocationEnum;
  /**
   * Гендер
   * @type {ToiletResDtoPersonEnum}
   * @memberof ToiletResDto
   */
  person: ToiletResDtoPersonEnum;
  /**
   *
   * @type {number}
   * @memberof ToiletResDto
   */
  floor: number;
  /**
   * Уникальный идентификатор туалета
   * @type {number}
   * @memberof ToiletResDto
   */
  id: number;
  /**
   * Список оценок туалета
   * @type {Array<ToiletRatingResDto>}
   * @memberof ToiletResDto
   */
  ratings: Array<ToiletRatingResDto>;
  /**
   * Дата создания записи
   * @type {Date}
   * @memberof ToiletResDto
   */
  createdAt: Date;
  /**
   * Дата последнего обновления
   * @type {Date}
   * @memberof ToiletResDto
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const ToiletResDtoLocationEnum = {
  FirstBuilding: "first_building",
  ThirdBuilding: "third_building",
  SecondBuilding: "second_building",
} as const;
export type ToiletResDtoLocationEnum =
  (typeof ToiletResDtoLocationEnum)[keyof typeof ToiletResDtoLocationEnum];

/**
 * @export
 */
export const ToiletResDtoPersonEnum = {
  Man: "man",
  Woman: "woman",
  Universal: "universal",
} as const;
export type ToiletResDtoPersonEnum =
  (typeof ToiletResDtoPersonEnum)[keyof typeof ToiletResDtoPersonEnum];

/**
 * Check if a given object implements the ToiletResDto interface.
 */
export function instanceOfToiletResDto(value: object): value is ToiletResDto {
  if (!("location" in value) || value["location"] === undefined) return false;
  if (!("person" in value) || value["person"] === undefined) return false;
  if (!("floor" in value) || value["floor"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("ratings" in value) || value["ratings"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function ToiletResDtoFromJSON(json: any): ToiletResDto {
  return ToiletResDtoFromJSONTyped(json, false);
}

export function ToiletResDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ToiletResDto {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    location: json["location"],
    person: json["person"],
    floor: json["floor"],
    id: json["id"],
    ratings: (json["ratings"] as Array<any>).map(ToiletRatingResDtoFromJSON),
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function ToiletResDtoToJSON(json: any): ToiletResDto {
  return ToiletResDtoToJSONTyped(json, false);
}

export function ToiletResDtoToJSONTyped(
  value?: ToiletResDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    location: value["location"],
    person: value["person"],
    floor: value["floor"],
    id: value["id"],
    ratings: (value["ratings"] as Array<any>).map(ToiletCreateRatingDtoToJSON),
    createdAt: value["createdAt"].toISOString(),
    updatedAt: value["updatedAt"].toISOString(),
  };
}
