/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Базовая DTO для Analytics
 * @export
 * @interface AnalyticsCreate
 */
export interface AnalyticsCreate {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsCreate
     */
    idToilet: number;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsCreate
     */
    soap: boolean;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsCreate
     */
    conditionRoom: number;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsCreate
     */
    test: boolean;
}

/**
 * Check if a given object implements the AnalyticsCreate interface.
 */
export function instanceOfAnalyticsCreate(value: object): value is AnalyticsCreate {
    if (!('idToilet' in value) || value['idToilet'] === undefined) return false;
    if (!('soap' in value) || value['soap'] === undefined) return false;
    if (!('conditionRoom' in value) || value['conditionRoom'] === undefined) return false;
    if (!('test' in value) || value['test'] === undefined) return false;
    return true;
}

export function AnalyticsCreateFromJSON(json: any): AnalyticsCreate {
    return AnalyticsCreateFromJSONTyped(json, false);
}

export function AnalyticsCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'idToilet': json['id_toilet'],
        'soap': json['soap'],
        'conditionRoom': json['condition_room'],
        'test': json['test'],
    };
}

export function AnalyticsCreateToJSON(json: any): AnalyticsCreate {
    return AnalyticsCreateToJSONTyped(json, false);
}

export function AnalyticsCreateToJSONTyped(value?: AnalyticsCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id_toilet': value['idToilet'],
        'soap': value['soap'],
        'condition_room': value['conditionRoom'],
        'test': value['test'],
    };
}

