/* tslint:disable */
/* eslint-disable */
/**
 * QR Toilet API
 * API для оценки состояния туалетов по QR кодам
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsToiletRating
 */
export interface ModelsToiletRating {
    /**
     * 
     * @type {string}
     * @memberof ModelsToiletRating
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsToiletRating
     */
    conditionRoom?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsToiletRating
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsToiletRating
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsToiletRating
     */
    soapAvailable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsToiletRating
     */
    toiletId?: number;
}

/**
 * Check if a given object implements the ModelsToiletRating interface.
 */
export function instanceOfModelsToiletRating(value: object): value is ModelsToiletRating {
    return true;
}

export function ModelsToiletRatingFromJSON(json: any): ModelsToiletRating {
    return ModelsToiletRatingFromJSONTyped(json, false);
}

export function ModelsToiletRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsToiletRating {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        'conditionRoom': json['condition_room'] == null ? undefined : json['condition_room'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'soapAvailable': json['soap_available'] == null ? undefined : json['soap_available'],
        'toiletId': json['toilet_id'] == null ? undefined : json['toilet_id'],
    };
}

export function ModelsToiletRatingToJSON(json: any): ModelsToiletRating {
    return ModelsToiletRatingToJSONTyped(json, false);
}

export function ModelsToiletRatingToJSONTyped(value?: ModelsToiletRating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'condition_room': value['conditionRoom'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'soap_available': value['soapAvailable'],
        'toilet_id': value['toiletId'],
    };
}

