/* tslint:disable */
/* eslint-disable */
/**
 * QR Toilet API
 * API для оценки состояния туалетов по QR кодам
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsToilet
 */
export interface ModelsToilet {
    /**
     * 
     * @type {string}
     * @memberof ModelsToilet
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsToilet
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsToilet
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsToilet
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsToilet
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsToilet interface.
 */
export function instanceOfModelsToilet(value: object): value is ModelsToilet {
    return true;
}

export function ModelsToiletFromJSON(json: any): ModelsToilet {
    return ModelsToiletFromJSONTyped(json, false);
}

export function ModelsToiletFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsToilet {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsToiletToJSON(json: any): ModelsToilet {
    return ModelsToiletToJSONTyped(json, false);
}

export function ModelsToiletToJSONTyped(value?: ModelsToilet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'rating': value['rating'],
        'updated_at': value['updatedAt'],
    };
}

