/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestCreate
 */
export interface TestCreate {
    /**
     * 
     * @type {string}
     * @memberof TestCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreate
     */
    description: string;
}

/**
 * Check if a given object implements the TestCreate interface.
 */
export function instanceOfTestCreate(value: object): value is TestCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function TestCreateFromJSON(json: any): TestCreate {
    return TestCreateFromJSONTyped(json, false);
}

export function TestCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function TestCreateToJSON(json: any): TestCreate {
    return TestCreateToJSONTyped(json, false);
}

export function TestCreateToJSONTyped(value?: TestCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

